CREATE TABLE "Customers" (
	-- mã khách hàng
	"id_customer" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"sex" CHAR(1) NOT NULL,
	"birthday" DATE NOT NULL,
	-- Contract
	"email" VARCHAR(255) NOT NULL,
	-- Contract
	"phonenumber" INTEGER NOT NULL,
	"username" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_customer")
);


COMMENT ON COLUMN "Customers"."id_customer" IS 'mã khách hàng';
COMMENT ON COLUMN "Customers"."email" IS 'Contract';
COMMENT ON COLUMN "Customers"."phonenumber" IS 'Contract';


CREATE TABLE "Employees" (
	"id_employee" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"sex" CHAR(1) NOT NULL,
	"birthday" DATE NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"phonenumber" INTEGER NOT NULL,
	"username" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_employee")
);




CREATE TABLE "Hotels" (
	"id_hotel" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"address" TEXT NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"phonenumber" INTEGER NOT NULL,
	"description " TEXT NOT NULL,
	PRIMARY KEY("id_hotel")
);




CREATE TABLE "Rooms" (
	"id_room" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_hotel" INTEGER NOT NULL,
	"id_type" INTEGER NOT NULL,
	"id_service" INTEGER NOT NULL,
	"num" INTEGER NOT NULL,
	"status " CHAR(1) NOT NULL,
	PRIMARY KEY("id_room")
);




CREATE TABLE "Types" (
	"id_type" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"area" INTEGER NOT NULL,
	"single_bed" SMALLINT NOT NULL,
	"double_bed" SMALLINT NOT NULL,
	"base_price " DOUBLE PRECISION NOT NULL,
	PRIMARY KEY("id_type")
);




CREATE TABLE "Services" (
	"id_service" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"breakfast" BOOLEAN NOT NULL,
	"wifi" BOOLEAN NOT NULL,
	"frigde" BOOLEAN NOT NULL,
	"bathtub" BOOLEAN NOT NULL,
	"description " TEXT NOT NULL,
	PRIMARY KEY("id_service")
);




CREATE TABLE "Bookings" (
	"id_booking" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_customer" INTEGER NOT NULL,
	"date_booking" INTERVAL NOT NULL,
	"time_check_in" INTERVAL NOT NULL,
	"time_check_out" INTERVAL NOT NULL,
	"status" CHAR(1) NOT NULL,
	PRIMARY KEY("id_booking")
);




CREATE TABLE "Details" (
	"id_detail" INTEGER NOT NULL,
	"id_booking" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_room" INTEGER NOT NULL,
	"num_customer" SMALLINT NOT NULL,
	"total_price" DOUBLE PRECISION NOT NULL,
	PRIMARY KEY("id_detail")
);




CREATE TABLE "Payments" (
	"id_payment" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_booking" INTEGER NOT NULL,
	"total_price" DOUBLE PRECISION NOT NULL,
	"method" CHAR(1) NOT NULL,
	"date" INTERVAL NOT NULL,
	"status" CHAR(1),
	PRIMARY KEY("id_payment")
);



ALTER TABLE "Hotels"
ADD FOREIGN KEY("id_hotel") REFERENCES "Rooms"("id_hotel")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Types"
ADD FOREIGN KEY("id_type") REFERENCES "Rooms"("id_type")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Services"
ADD FOREIGN KEY("id_service") REFERENCES "Rooms"("id_service")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Customers"
ADD FOREIGN KEY("id_customer") REFERENCES "Bookings"("id_customer")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Bookings"
ADD FOREIGN KEY("id_booking") REFERENCES "Details"("id_booking")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Rooms"
ADD FOREIGN KEY("id_room") REFERENCES "Details"("id_room")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Bookings"
ADD FOREIGN KEY("id_booking") REFERENCES "Payments"("id_booking")
ON UPDATE NO ACTION ON DELETE NO ACTION;